### PR TITLE
Update BluetoothProtocol.java

### PR DESCRIPTION
**Pull request by NixToDo**
Added "Locale.ENGLISH" to prevent .format using locales witch have a comma instead of a dot as a decimal separator. (Later it will fail to convert the string back to float if a comma was used as decimal separator.)

### CODE REVIEW

**Comment by Lauszus** [comment]
It looks like you are missing an import: https://travis-ci.org/Lauszus/LaunchPadFlightControllerAndroid/builds/121375946#L1296.

**Comment by Lauszus** [comment]
I.e. you forgot to add:

``` java
import java.util.Locale;
```

**Comment by Lauszus** [comment]
While you are at it, can you please also fix these ones: https://github.com/Lauszus/LaunchPadFlightControllerAndroid/blob/29637205cec9e9ef28e91744dd0417cc21a5d3d3/app/src/main/java/com/lauszus/launchpadflightcontrollerandroid/app/InfoFragment.java#L78-L85.

**Comment by NixToDo** [comment]
Yes, I have forgotten the import...

**Comment by NixToDo** [comment]
Added the InfoFragment.java changes

**Comment by Lauszus** [comment]
@NixToDo I just merged you PR.

Thanks: https://github.com/Lauszus/LaunchPadFlightControllerAndroid/commit/0e7ead239b60fc78041ef2c1be074a50f27b47c0 :)

**Pull request closed without merging**
